package com.claro.rules.filtrado

import com.claro.cpymes.dto.KeyCatalogDTO;
import com.claro.cpymes.dto.LogDTO;
import com.claro.cpymes.entity.AlarmCatalogEntity;
import com.claro.cpymes.enums.SeverityEnum;
import com.claro.cpymes.enums.StateEnum;
import com.claro.cpymes.util.Constant;

import java.util.HashMap;


global HashMap<KeyCatalogDTO, AlarmCatalogEntity> catalog;

rule "Marcacion Severity"
	no-loop  
	salience 0
	when
		$log:LogDTO(OID != null && OID.length()>2)
	then
		//Consultando se el evento se encuentra dentro del Catalogo para PyMES		
		if(catalog.containsKey($log.getKey())){
			AlarmCatalogEntity catalogEntity = (AlarmCatalogEntity) catalog.get($log.getKey());
			$log.setSeverity(catalogEntity.getSeverity());
			$log.setMessageDRL($log.getTranslatedLine());
			if($log.getNameEvent()==null || $log.getNameEvent().length()==0){
				$log.setNameEvent(catalogEntity.getTextAlarm().trim());				
			}	
		} else{
			$log.setSeverity(SeverityEnum.NI.getValue());
			$log.setMessageDRL($log.getTranslatedLine());
		}
		$log.setRelevant(true);
		$log.setState(StateEnum.NO_SAVE.getValue());
		
		update($log);	
		
end

	
rule "Afectacion Masiva"
	salience -1
    when
    	$log: LogDTO(
        	nameEvent in (
        		"mplsLdpSessionDown",
        		"mplsTunnelDown",
        		"hwAlarmEthernetPortOffline",
        		"hwOpticsPowerOutOfRangeAlarmTrap",
        		"hwGonuLinkLOFTrap",
        		"GonuLinkLOF",
        		"hwGponnniOntLinkLosAlarmTrap",
        		"GponnniOntLinkLosAlarm",
        		"hwGponOltLOSAlarmTrap",
        		"GponOltLOSAlarm",
        		"hwGponProfNumerousOntsPowerOffAlarmTrap",
        		"hwGponProfOntIsRogueOntAlarmTrap",
        		"hwXponProfOltLOSAlarmTrap",
        		"zxGponOltLOS"),
			severity in (
	    		"AS",
	    		"PAS",
	    		"NAS"))
    then
    	StringBuffer buffer = new StringBuffer(); 
        buffer.append("AFECTACIÓN MASIVA ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
        $log.setSendIVR(true);
end



rule AfectacionMasivaCorelacion
	salience -1
    when
    	$log: LogDTO(
        	nameEvent in (
        		"hwGponEthernetPortSignalRecoverAlarmTrap",
        		"hwGponEthernetPortLossOfSignelOccurAlarmTrap",        		
        		"linkDown",
        		"LinkDown",        		
        		"tmnxEqPortFailure",        		
        		"tmnxEqPortSFPRemoved",
        		"hwAlarmEthernetMacLost",        		
        		"hwAlarmLOSOccurs",
        		"hwGonuLinkLOSTrap",
        		"GonuLinkLOS",
        		"hwGponOntSFAlarmTrap",
        		"GponOntSFAlarm",
        		"hwGponOntLOSAlarmTrap",
        		"GponOntLOSAlarm",
        		"hwGponOntSUFAlarmTrap",
        		"GponOntSUFAlarm",
        		"hwGponOntConfigRecoveryFailAlarmTrap", 		
        		"GponOntConfigRecoveryFailAlarm",   
        		"hwGponOntResetByWatchdogAlarmTrap",     		
        		"GponOntResetByWatchdogAlarm",        		
        		"hwGponONTGEMPortCfgChangeTrap",
        		"zxGponOltLOSi",
        		"zxGponOltLOFi",
        		"zxGponOltSFi",
        		"zxGponOntLOS",
        		"zxGponOntLOF",
        		"zxGponOltLOS",
        		"zxGponOltLOF"),
    		severity in (
    			"AS",
    			 "PAS"))
    then	
		$log.setCorrelation(true);
		$log.setNameCorrelation("AfectacionMasiva");
		$log.setNameDeviceCorrelate($log.getName());
		$log.setState(StateEnum.ACTIVO.getValue());
		$log.setSendIVR(true);
end


rule "Reinicio Puerto Equipo Intermitencia PAS"
	salience -1
	when			
		$log: LogDTO(
        	nameEvent in (
        		"tmnxEqPortSFPRemoved",        		
        		"hwAlarmEthernetMacLost",        		      		
        		"GponOntSUFAlarm",      		
        		"hwGponOntSUFAlarmTrap",        		        		
        		"GponOntConfigRecoveryFailAlarm",        		
        		"hwGponOntConfigRecoveryFailAlarmTrap",        		        		
        		"GponOntResetByWatchdogAlarm",        		
        		"hwGponOntResetByWatchdogAlarmTrap",        		        		
        		"hwGponONTGEMPortCfgChangeTrap",        		
        		"hwAlarmEthernetPortStatusChanges"),
    		severity in (
    			"AS",
    			"PAS",
    			"NAS"))
    then
    	StringBuffer buffer = new StringBuffer(); 
        buffer.append("REINICIOS DE PUERTO O EQUIPO (INTERMITENCIA) ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
end



/*/No found
rule "Posible Afectacion"
	salience -1
	when			
		$log: LogDTO(
        	nameEvent in (
        		"tmnxEqPortError",        		       		
        		"tmnxEqPortEtherAlarm",        		    		      		
        		"tmnxEndPointTxActiveChanged",  
        		"svcPersistencyProblem",        		        		
        		"hostConnectivityLost",        		
        		"hwPortStateChangeInfoTrap",        		        		
        		"hwAlarmUpstreamPortConnectfail",    
        		"hwGponOntHardwareFaultyAlarmTrap",        		        		
        		"hwGponOntE1T1PortStatusAbnormalAlarmTrap",        		
        		"hwGponTcontProfileOperateTrap",        		
        		"hwXponPortStateChangeTrap",
        		"hwGponProfOltOpticalTransceiverAbsentAlarmTrap",        		    		
        		"hwGponProfOntSFAlarmTrap",        		
        		"hwGponProfOntLOFAlarmTrap",        		
        		"hwGponProfRogueOntDisapearAlarmTrap",
        		"hwXponProfLocalOpticalModuleRecoverAlarmThresAlarmTrap",
        		"hwXponProfLocalOpticalModuleRecoverWarnThresAlarmTrap",
        		"hwGponProfOntE1T1PortStatusAbnormalAlarmTrap",
        		"zxGponBWProfileIndex",
        		"zxOnuTrafficMgmtUnitTcontUpBWIdxPtr",
        		"zxGponGemPortType",
        		"zxGponGemPortTcontIdx",
        		"zxGponVlanPortIndex",
        		"zxGponVlanPortMode",
        		"zxGponVlanPortPvid"),
    		severity in (
    			"AS",
    			 "PAS"))
    then
    	StringBuffer buffer = new StringBuffer();
        buffer.append("SERVICIO CAIDO ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        buffer.append("<hr/>");
        buffer.append(" ORIGINAL KOU: <b>");
        buffer.append($log.getTranslatedLine()+"</b>");
        
        $log.setMessageDRL(buffer.toString());	
end*/



rule "Problema Alimentacion Energia"
	salience -1
	when		
		$log: LogDTO(
        	nameEvent in (
        		"tmnxEqPowerSupplyFailure",
        		"tmnxEqPowerSupplyRemoved",
        		"hwDevPowerInputFaultTrap",
        		"hwDevPowerInputRecoverTrap",
        		"powerConnFaultAlarm",
        		"acCommFailAlarm",
        		"acInputPowerOffAlarm",
        		"acInputLoopSwtichAlarm",
        		"hwSwitchoverTrap",
        		"hwVlanifDownTrap",
        		"hwGponProfNumerousOntsPowerOffAlarmTrap"), 
    		severity in (
    			"AS",
    			 "PAS",
    			 "NAS"))
    then
    	StringBuffer buffer = new StringBuffer();
        buffer.append("PROBLEMA EN ALIMENTACIÓN (ENERGÍA) ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
end

rule "Problema Tarjeta Modulo Equipo"
	salience -1
	when		
		$log: LogDTO(
        	nameEvent in (
        		"tmnxEqCardFailure",
        		"tmnxEqCardRemoved",
        		"tmnxEqFlashDataLoss",
        		"sbiBootConfig",
        		"sbiBootSnmpd",
        		"hwDevBoardDisappearedTrap",
        		"hwDevBoardStaChgOffLineTrap",
        		"hwDevBoardMisMatchTrap",
        		"hwDevBoardHardFaultTrap",
        		"hwDevBoardFaultTrap",
        		"zxGponOltPEEi",
        		"zxGponOntPee"), 
    		severity in (
    			"AS",
    			 "PAS",
    			 "NAS"))
    then    	
		StringBuffer buffer = new StringBuffer();
	    buffer.append("PROBLEMA EN TARJETA, MODULO O EQUIPO ");
	    buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
	    $log.setState(StateEnum.ACTIVO.getValue());
end



rule "Servicio Caido Puerto NoMAC AS"
	salience -1
	when		
		$log: LogDTO(
        	nameEvent in (
        		"linkDown",
        		"LinkDown",
        		"tmnxEqPortFailure",
        		"tmnxEqPortSFPRemoved",
        		"hwAlarmEthernetMacLost", 
        		"hwAlarmLOSOccurs",
        		"GonuLinkLOS",
        		"hwGonuLinkLOSTrap",
        		"GponOntSFAlarm/",
        		"hwGponOntSFAlarmTrap",
        		"GponOntLOSAlarm/",
        		"hwGponOntLOSAlarmTrap",
        		"zxGponOltLOSi",
        		"zxGponOltLOFi",
        		"zxGponOltSFi",
        		"zxGponOntLOS",
        		"zxGponOntLOF",
        		"zxGponOltLOS",
        		"zxGponOltLOF",
        		"zxGponOnuOpticalTransceiverLos"
        		), 
    		severity in (
    			"AS",
    			"PAS",
    			"NAS"))
											
       
    then
	
        StringBuffer buffer = new StringBuffer();
        buffer.append("SERVICIO CAIDO (puerto caído, puerto dañado, no aprende MAC) ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
        $log.setSendIVR(true);        
end




rule "Temperatura Alta"
	salience -1
	when	
		$log: LogDTO(
        	nameEvent in (
        		"tmnxEnvTempTooHigh",
        		"envCommAlarm",
        		"hwOpticsPortTemperatureHighAlarmTrap",
        		"hwDevBoardTemperatureTooHighTrap"), 
    		severity in (
    			"AS",
    			 "PAS",
    			 "NAS"))  
    then
	    StringBuffer buffer = new StringBuffer();
        buffer.append("TEMPERATURA ALTA ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        buffer.append("<hr/>");
        buffer.append(" ORIGINAL KOU: <b>");
        buffer.append($log.getTranslatedLine()+"</b>");
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
end




rule "Atenuacion Potencia Optica"
	salience -1
	when	
		$log: LogDTO(
        	nameEvent in (
        		"hwOpticsTxPowerOutOfRangeAlarmTrap",
        		"hwOpticsRxPowerOutOfRangeAlarmTrap",
        		"hwGonuTxPowerExceedThreAlarmTrap",
        		"hwGponRemoteOpticalModuleExceedAlarmThresAlarmTrap",
        		"hwGponLocalOpticalModuleExceedWarnThresAlarmTrap",
        		"hwXponProfLocalOpticalModuleExceedAlramThresAlarmTrap",
        		"hwXponProfRemoteOpticalModuleExceedAlarmThresAlarmTrap",
        		"hwXponProfLocalOpticalModuleExceedWarnThresAlarmTrap",
        		"zxGponOltRxPowerAbnormalInformi",
        		"zxGponOltRxPowerAlarmi"),
    		severity in (
    			"AS",
    			 "PAS",
    			 "NAS"))
    then
        StringBuffer buffer = new StringBuffer();
        buffer.append("VARIACIÓN EN POTENCIA OPTICA ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
end

rule "Caida Troncal OLT"
	salience -1
	when	
		$log: LogDTO(
        	nameEvent in (
        		"hwXponProfOltLOSAlarmTrap",
        		"zxGponOltLOS"),
    		severity in (
    			"AS",
    			 "PAS",
    			 "NAS"))
    then
        StringBuffer buffer = new StringBuffer();
        buffer.append("CAIDA TRONCAL OLT ");
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getName());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.INTERFACE);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getInterFace());
        buffer.append(Constant.BOLD_END);
        buffer.append(Constant.DESCRIPCION);
        buffer.append(Constant.BOLD_INIT);
        buffer.append($log.getDescriptionAlarm());
        buffer.append(Constant.BOLD_END);
        
        $log.setMessageDRL(buffer.toString());
        $log.setState(StateEnum.ACTIVO.getValue());
end


